version: '3'
services:
  redis: 
    image: redis:alpine
    container_name: sc-redis
    restart: always
    volumes:
      - ../data/redis:/data
    environment:
      - REDIS_PASSWORD=123456
    networks:
      - sc-net
    ports:
      - 6379:6379
    env_file: .env  #加载环境变量文件，批量维护环境变量

  mysql:
    image: mysql:5.7
    container_name: sc-mysql
    restart: always
    networks:
      - sc-net
    ports:
      - 3306:3306
    volumes:
      - ../data/mysql:/var/lib/mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root

#  mysql-init:
#    image: mysql:5.7
#    command: /init-db.sh
#    networks:
#      - sc-net
#    volumes:
#      - ../auth/db:/sql/auth
#      - ../gateway/gateway-admin/src/main/db:/sql/gateway
#      - ../sysadmin/db:/sql/sysadmin
#      - ./init-db.sh:/init-db.sh
#    environment:
#      MYSQL_ROOT_PASSWORD: root

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: sc-rabbitmq
    restart: always
    volumes:
      - ../data/rabbitmq:/var/lib/rabbitmq/mnesia
    networks:
      - sc-net
    ports:
      - 5672:5672
      - 15672:15672
    env_file: .env

  elasticsearch:
    image: elasticsearch:5.6-alpine
    container_name: sc-elasticsearch
    restart: always
    environment:
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - node.name=elasticsearch_node_1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ../data/elasticsearch/data:/usr/share/elasticsearch/data
      - ../data/elasticsearch/logs:/usr/share/elasticsearch/logs
      - ./devops/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - sc-net
    ports:
      - 9200:9200
      - 9300:9300

  zipkin-server:
    image: openzipkin/zipkin
    container_name: sc-zipkin-server
    restart: always
    volumes:
      - ../data/zipkin-server/logs:/var/logs
    networks:
      - sc-net
    ports:
      - 9411:9411
    environment:
      - RABBIT_ADDRESSES=rabbitmq:5672
      - RABBIT_MQ_PORT=5672
      - RABBIT_PASSWORD=guest
      - RABBIT_USER=guest
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=http://elasticsearch:9200
    depends_on:
      - rabbitmq

  skywalking-oap:
    image: wutang/skywalking-oap:6.1.0
    container_name: skywalking-oap
    networks:
      - sc-net
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    restart: always
    ports:
      - 11800:11800
      - 12800:12800
    volumes:
      - ./devops/skywalking/config:/apache-skywalking-apm-bin/config:ro

  skywalking-ui:
    image: wutang/skywalking-ui:6.1.0
    container_name: skywalking-ui
    networks:
      - sc-net
    depends_on:
      - skywalking-oap
    links:
      - skywalking-oap
    restart: always
    ports:
      - 8080:8080
    environment:
      collector.ribbon.listOfServers: skywalking-oap:12800

  kibana:
    image: kibana:5.6.14
    container_name: sc-kibana
    restart: always
    volumes:
      - ../data/kibana/logs:/var/logs/kibana
      - ./devops/kibana.yml:/etc/kibana/kibana.yml
    networks:
      - sc-net
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  grafana:
    image: grafana/grafana
    container_name: sc-grafana
    restart: always
    volumes:
      - ../data/grafana/logs:/var/logs/grafana
    networks:
      - sc-net
    ports:
      - 3000:3000

  sentinel-dashboard:
    image: cike/sentinel-dashboard-docker:latest
    container_name: sc-sentinel-dashboard
    restart: always
    networks:
      - sc-net
    ports:
      - 8021:8021
    env_file: .env

networks:
  sc-net:
    external: false